#!/bin/bash

# 135sb07
#for NUMBER in $(seq 1431 1 1434)
#do
#./bdn_sort_20131203 /music/bpt1/bpt/bdn/2013/setup/datafiles/run0$NUMBER
#./deadtime_correction_135sb7 ./bdn.root
#cp -a ./bdn.root /music/bpt1/bpt/bdn/shane/135sb/rootfiles/run0$NUMBER.root
#done

# 135sb08
for NUMBER in $(seq 1435 1 1533)
do
#./bdn_sort_20131203 /music/bpt1/bpt/bdn/2013/setup/datafiles/run0$NUMBER
./bdn_sort_20140613 /music/bpt1/bpt/bdn/2013/setup/datafiles/run0$NUMBER posts 135sb08
cp -a ./bdn.root /music/bpt1/bpt/bdn/shane/135sb/rootfiles/run0$NUMBER.root
done
