#!/bin/bash

for NUMBER in $(seq 1570 1 1651)
do
./bdn_sort_20131125 /music/bpt1/bpt/bdn/2013/setup/datafiles/run0$NUMBER
./deadtime_correction_140i1 ./bdn.root
cp -a ./bdn.root /music/bpt1/bpt/bdn/shane/140i/rootfiles/run0$NUMBER.root
done
